FROM python:3.6-slim

MAINTAINER Gabriele Giammatteo <gabriele.giammatteo@eng.it>


RUN apt-get update
RUN apt-get -y install git

RUN pip install benchsuite.core==2.4.0 benchsuite.cli==2.1.2 benchsuite.backends==2.3.0 benchsuite.stdlib==2.5.0


ENV BENCHSUITE_CONFIG_FOLDER /

ENTRYPOINT ["benchsuite", "-vv", "multiexec"]
