FROM python:3.6-slim

MAINTAINER Gabriele Giammatteo <gabriele.giammatteo@eng.it>


RUN apt-get update
RUN apt-get -y install git

RUN pip install benchsuite.core==2.2.1 benchsuite.cli==2.1.0 benchsuite.backends==2.1.0 benchsuite.stdlib==2.2.1


ENV BENCHSUITE_CONFIG_FOLDER /

ENTRYPOINT ["benchsuite", "-vvv", "multiexec"]
