FROM python:3.6-slim

MAINTAINER Gabriele Giammatteo <gabriele.giammatteo@eng.it>


RUN apt-get update
RUN apt-get -y install git

RUN pip install benchsuite.core==2.0.0b6 benchsuite.cli==2.0.0b7 benchsuite.backends==2.0.0b0 benchsuite.stdlib==2.0.0b5


ENV BENCHSUITE_CONFIG_FOLDER /

ENTRYPOINT ["benchsuite", "-vvv", "multiexec"]
