FROM python:3.6-slim

MAINTAINER Gabriele Giammatteo <gabriele.giammatteo@eng.it>


RUN apt-get update
RUN apt-get -y install git

RUN pip install benchsuite.scheduler==1.0.0

ENTRYPOINT ["benchsuite-scheduler", "--config", "/tmp/config"]
