FROM python:3.6-slim

MAINTAINER Gabriele Giammatteo <gabriele.giammatteo@eng.it>


RUN pip install benchsuite.core==2.6.0 benchsuite.rest==2.3.0 benchsuite.backends==2.5.0 benchsuite.stdlib==2.7.0
EXPOSE 5000

ENV BENCHSUITE_CONFIG_FOLDER /

ENTRYPOINT ["benchsuite-rest", "run"]
